#Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada
n = int(input('Digite um número para ver a sua tabuada: '))
print('-'*12)
print(f'{n} x {0:2} = {n*0}')
print(f'{n} x {1:2} = {n*1}')
print(f'{n} x {2:2} = {n*2}')
print(f'{n} x {3:2} = {n*3}')
print(f'{n} x {4:2} = {n*4}')
print(f'{n} x {5:2} = {n*5}')
print(f'{n} x {6:2} = {n*6}')
print(f'{n} x {7:2} = {n*7}')
print(f'{n} x {8:2} = {n*8}')
print(f'{n} x {9:2} = {n*9}')
print(f'{n} x {10:2} = {n*10}')
print('-'*12)
